version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "fresh -c fresh.conf"
    # command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raise_tech
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  migrate:
    image: migrate/migrate
    # networks:
    #   - new
    volumes:
      - .:/migrations
    command: ["migrate", "-database", "mysql://root:password@tcp(0.0.0.0:3306)/raise_tech", "-path", "migrations", "up"]
    # command: ["-path", "/migrations", "-database",  "mysql://root:root@tcp(db:3306)/raise_tech", "up", "3"]
    links:
      - db

volumes:
  db-data:
    driver: local
# networks:
#   new:
